# Generated by Django 2.2.2 on 2020-04-08 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemedialMeasuresModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measures_taken', models.TextField(blank=True, max_length=500, null=True)),
                ('has_notified_regulators', models.CharField(choices=[(None, 'Choose an option'), ('Yes', 'Yes'), ('No', 'No')], max_length=200)),
                ('regulators_notified', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Remedial Measure',
                'verbose_name_plural': 'Remedial Measures',
            },
        ),
        migrations.CreateModel(
            name='RepresentativeModel',
            fields=[
                ('representative_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_names', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('relationship_to_complainant', models.CharField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Representative',
                'verbose_name_plural': 'Representative',
            },
        ),
        migrations.CreateModel(
            name='DataControllerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_names', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('data_protection_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_officer_contacted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Controller',
                'verbose_name_plural': 'Data Controllers',
            },
        ),
        migrations.CreateModel(
            name='DataBreachModel',
            fields=[
                ('data_breach_id', models.AutoField(primary_key=True, serialize=False)),
                ('nature', models.CharField(max_length=100)),
                ('date_of_awareness', models.DateField(blank=True, null=True, verbose_name='date_of_awareness')),
                ('subject_personal_data', models.CharField(max_length=100)),
                ('personal_data_categories', models.CharField(max_length=100)),
                ('number_of_subjects', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, max_length=500, null=True)),
                ('risk_of_harm', models.TextField(blank=True, max_length=500, null=True)),
                ('date_serviced', models.DateTimeField(blank=True, null=True, verbose_name='date_received')),
                ('date_implemented', models.DateTimeField(blank=True, null=True, verbose_name='date_implemented')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='request date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_approved_by', to=settings.AUTH_USER_MODEL)),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breach_implemented_by', to=settings.AUTH_USER_MODEL)),
                ('measures', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protect.RemedialMeasuresModel')),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protect.RepresentativeModel')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
        migrations.CreateModel(
            name='ComplaintModel',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('name_of_respondent', models.CharField(max_length=100)),
                ('address_of_respondent', models.CharField(max_length=200)),
                ('dpo_contacted', models.CharField(max_length=200)),
                ('details_of_complaint', models.TextField(blank=True, max_length=500, null=True)),
                ('date_serviced', models.DateTimeField(blank=True, null=True, verbose_name='date_received')),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('date_implemented', models.DateTimeField(blank=True, null=True, verbose_name='date_implemented')),
                ('date_of_request', models.DateTimeField(auto_now_add=True, verbose_name='request date')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('complainant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('implemented_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implemented_by', to=settings.AUTH_USER_MODEL)),
                ('representative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='protect.RepresentativeModel')),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
            },
        ),
    ]
