# Generated by Django 3.0.6 on 2020-05-21 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databreachmodel',
            options={'verbose_name': 'Data Breach', 'verbose_name_plural': 'Data Breaches'},
        ),
    ]
