# Generated by Django 3.0.6 on 2020-06-03 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200521_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('1', 'Director Legal'), ('2', 'admin'), ('3', 'I.T. Officer'), ('4', 'Service Desk')], default='complainant', max_length=200),
        ),
    ]
