# Generated by Django 3.0.6 on 2020-06-07 21:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to=web.models.upload_location)),
                ('date_published', models.DateField(auto_now_add=True, verbose_name='Date Published')),
                ('date_updated', models.DateField(auto_now_add=True, verbose_name='Date Updated')),
                ('reference_link', models.CharField(max_length=5000)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
    ]
